### ISSUE TITLE
update to libv8 6.0

### ISSUE THREAD

**Issue by seanmakesgames** [discourse/mini_racer#65] opened 2017-08-24 16:41 UTC
am running my test suite against 6.0.286.54.0beta1
wanted a place to write down the results. :)
@SamSaffron @ignisf

**Comment by seanmakesgames** [comment] 2017-08-24 18:32
I'm getting 
```
mkdir -p tmp/x86_64-darwin15/mini_racer_extension/2.2.4
cd tmp/x86_64-darwin15/mini_racer_extension/2.2.4
/Users/user/.rvm/rubies/ruby-2.2.4/bin/ruby -I. ../../../../ext/mini_racer_extension/extconf.rb
checking for main() in -lpthread... yes
checking for main() in -lobjc... yes
creating Makefile
cd -
cd tmp/x86_64-darwin15/mini_racer_extension/2.2.4
/usr/bin/make
compiling ../../../../ext/mini_racer_extension/mini_racer_extension.cc
clang: warning: argument unused during compilation: '-rdynamic'
linking shared-object mini_racer_extension.bundle
clang: warning: libstdc++ is deprecated; move to libc++
ld: unknown option: --start-group
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mini_racer_extension.bundle] Error 1
rake aborted!
Command failed with status (2): [/usr/bin/make...]
/Users/user/.rvm/gems/ruby-2.2.4/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:157:in `block (2 levels) in define_compile_tasks'
/Users/user/.rvm/gems/ruby-2.2.4/gems/rake-compiler-0.9.9/lib/rake/extensiontask.rb:156:in `block in define_compile_tasks'
/Users/user/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `eval'
/Users/user/.rvm/gems/ruby-2.2.4/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => compile => compile:x86_64-darwin15 => compile:mini_racer_extension:x86_64-darwin15 => copy:mini_racer_extension:x86_64-darwin15:2.2.4 => tmp/x86_64-darwin15/mini_racer_extension/2.2.4/mini_racer_extension.bundle
(See full trace by running task with --trace)
```
on `rake clean compile`

is my platform built @ignisf or am I doing something else wrong?

**Comment by seanmakesgames** [comment] 2017-08-24 19:11
looks like this issue is #66 and I think related to the --start-group linker error (unknown option)
The weird thing is that it's inconsistent on when it shows up. Will resolve on other issue.

**Comment by ignisf** [comment] 2017-08-24 19:18
https://github.com/cowboyd/libv8/commit/99774366a4c369e8383e208c907e52c740156c0f

**Comment by seanmakesgames** [comment] 2017-08-24 19:29
haha thanks @ignisf -- can't tell if this is introducing the issue or fixing it? Assuming introduces, but don't understand how this is happening on mini_racer mainline (through bundler) when dependency is @ 5.9
Maybe my grasp of what bundler is doing is poor. :\

**Comment by ignisf** [comment] 2017-08-24 19:36
I'll revert this commit and release another beta. Bundler is not selecting the correct version of libv8 I think. Try uninstalling 6.*. Sorry for taking so long to respond. My ISP has a broken optical connection.

**Comment by seanmakesgames** [comment] 2017-08-24 19:37
it's all good @ignisf! Thanks for the response.
Good luck with your internet!

**Comment by seanmakesgames** [comment] 2017-08-24 19:45
You were right-- uninstalling 6.0 got the correct libv8 version to load up, and has isolated the issue to 6.0beta. Thanks for the help @ignisf :)
Awaiting new beta for testing.

**Comment by seanmakesgames** [comment] 2017-08-25 14:35
Everything works @ignisf thanks!
Running test suite now.

**Comment by seanmakesgames** [comment] 2017-08-25 14:56
Tests all check out. :)

**Comment by ignisf** [comment] 2017-08-26 16:48
6.0 released 🎉

**Comment by krzysiek1507** [comment] 2017-08-29 08:03
@seanmakesgames are you testing it on production again? :D

**Comment by ignisf** [comment] 2017-08-29 08:17
That's just how he roll :)

**Comment by krzysiek1507** [comment] 2017-08-29 08:20
Can you see significant performance improve?

**Comment by seanmakesgames** [comment] 2017-08-29 15:13
Haha, nah-- was running against my test suite. I'll be 'testing on production' once mini_racer has upped its version number. ;)

I didn't do any benchmarking as part of my test cases because I run them multicore. It did 'feel' faster, but that's not useful information. :P

**Comment by krzysiek1507** [comment] 2017-08-29 15:50
Haha. When I updated Node to 8.4.0 (with v8 6.0) it was about 40% faster.
Do you have any ETA? :)

**Comment by seanmakesgames** [comment] 2017-08-29 15:59
That's a question for @SamSaffron

**Comment by SamSaffron** [comment] 2017-08-31 00:27
@krzysiek1507 I don't have an eta, but once @seanmakesgames is happy that 6.0 is stable I am happy to bounce the version. 

My initial testing definitely did not show a 40% improvement in my microbench maybe 5-10%

**Comment by SamSaffron** [comment] 2017-08-31 00:27
Note, I am travelling over the next 3 weeks so I am not 100% sure I will be super fast here.

**Comment by krzysiek1507** [comment] 2017-08-31 07:40
Thanks, guys! You are doing great work!

**Comment by seanmakesgames** [comment] 2017-08-31 15:20
@SamSaffron 6.0 appears stable. I'm good with a rev bump.

**Comment by krzysiek1507** [comment] 2017-09-01 06:27
When I installed it from my [repo](https://github.com/krzysiek1507/mini_racer/commit/458c7fafa7a0815e029ff2031e52964cbc54acbd) I saw error:
```
/bundle/bin/rake assets:precompile: symbol lookup error: /bundle/bundler/gems/mini_racer-458c7fafa7a0/lib/mini_racer_extension.so: undefined symbol: _ZN2v84base5debug27EnableInProcessStackDumpingEv
```

Version: `libv8 6.0.286.54.1 (x86_64-linux)`

**Comment by krzysiek1507** [comment] 2017-09-18 11:33
Any update on this?

**Comment by SamSaffron** [comment] 2017-09-21 16:09
Will do another release next week

**Comment by krzysiek1507** [comment] 2017-09-21 17:11
Thanks!

**Comment by SamSaffron** [comment] 2017-09-25 03:04
confirmed @ignisf  getting: 

/home/sam/.rbenv/versions/2.3.1/bin/ruby: symbol lookup error: /home/sam/Source/mini_racer/lib/mini_racer_extension.so: undefined symbol: _ZN2v84base5debug27EnableInProcessStackDumpingEv

on GCC with 6.0.286 , can you have a look?

**Comment by ignisf** [comment] 2017-09-25 07:57
morning, back from vacation, will try to check it out

**Comment by SamSaffron** [comment] 2017-09-25 07:58
cool, thanks!

**Comment by ignisf** [comment] 2017-10-23 22:09
the missing symbol was due to the reordering of the libraries. Who knew Google's wiki would lie... Should be fixed in master and the 6.0 branches

**Comment by ignisf** [comment] 2017-10-25 13:29
Released a version that fixes this.

**Comment by SamSaffron** [comment] 2017-12-04 20:13
@ignisf I would like to push us up to 6.2 which is latest stable, any chance you can do a build, then @seanmakesgames can validate it looks good?

**Comment by ignisf** [comment] 2017-12-04 20:24
I thought you'd never ask :P

**Comment by ignisf** [comment] 2017-12-05 13:40
beta up on rubygems

**Comment by seanmakesgames** [comment] 2017-12-05 16:49
received. mini_racer tests are passing. Running hackmud suite now.

**Comment by seanmakesgames** [comment] 2017-12-05 17:00
Tests pass. ✅

**Comment by ignisf** [comment] 2017-12-05 19:40
OK, will do a stable release asap

**Comment by ignisf** [comment] 2017-12-13 13:25
![image](https://user-images.githubusercontent.com/1153188/33941014-12f4b106-e009-11e7-9f61-c661baa614fa.png)

**Comment by ignisf** [comment] 2017-12-13 16:20
just an FYI, we will be losing FreeBSD support with this version due to lack of upstream support. I decided to not hold up the release more.

**Comment by seanmakesgames** [comment] 2017-12-13 19:06
Fine by me. ;)
I'm excited to see how this release performs in the live environment. 😄

**Comment by SamSaffron** [comment] 2017-12-14 07:39
OK, my plan for tomorrow is to bench it on Discourse!

**Comment by SamSaffron** [comment] 2017-12-15 01:45
This is not great... my bench suite for discourse is hanging ....

**Comment by seanmakesgames** [comment] 2017-12-15 02:11
That's strange. My full test suite passed. :\

**Comment by SamSaffron** [comment] 2017-12-15 03:54
oops @ignisf looks like 6.2 is hanging for me during script runs. I will try to build a repro for this. I wonder if this was a temporary bug in v8 or if it is fixed in 6.3

6.0 seems to work fine though.

**Comment by SamSaffron** [comment] 2017-12-15 03:56
the repro of the bug is to run: https://github.com/discourse/discourse/blob/master/script/benchmarks/markdown/bench.rb but that involves a full discourse install...

**Comment by ignisf** [comment] 2017-12-18 15:32
@SamSaffron, 

Just released 6.3 beta.

![image](https://user-images.githubusercontent.com/1153188/34113757-a29cf63a-e408-11e7-8487-81dbecbdd7f1.png)

**Comment by SamSaffron** [comment] 2017-12-18 20:44
Oh no :( looks like this is hanging as well, going to create a simple repro script here and ask v8 folks for help.

**Comment by ignisf** [comment] 2017-12-18 21:32
@SamSaffron, are you sure you're testing with mini_racer linked against the 6.3 beta and not by any chance linked against 6.2?

**Comment by SamSaffron** [comment] 2017-12-18 22:22
yes, 100% 6.3.292.48.0beta1 in my gemfile lock ... trying to build a repro

**Comment by SamSaffron** [comment] 2017-12-18 22:41
I am pretty sure this is the bug:

https://bugs.chromium.org/p/v8/issues/detail?id=6933

Can you compile 6.4 to confirm it is fixed there? This kind of sucks cause
it means we can not upgrade till 6.4 is released OR unless we backport it.

**Comment by SamSaffron** [comment] 2017-12-18 22:50
OK, v8 team say it backports very cleanly, can you try maybe adding that patch and doing another 6.3 release?

**Comment by ignisf** [comment] 2017-12-18 23:08
Hey, sounds good, will look into backporting.

**Comment by ignisf** [comment] 2017-12-18 23:25
https://github.com/cowboyd/libv8/commit/5777dbdea1109048fb91756b16ac00030aa49715

Will cut another release tomorrow if the CI passes tonight :)

**Comment by SamSaffron** [comment] 2017-12-19 00:27
Awesome! Thanks for that!

**Comment by ignisf** [comment] 2017-12-19 10:18
![image](https://user-images.githubusercontent.com/1153188/34152272-eb83479e-e4a5-11e7-9a16-4fe29bb58210.png)

**Comment by seanmakesgames** [comment] 2017-12-19 16:42
@SamSaffron let me know when you've tested the patch on this. I'll run my suite against it after.

**Comment by SamSaffron** [comment] 2017-12-20 01:17
Looking good on my side! @ignisf bench is no longer hanging, the bad news is that it that 6.3 appears slower than 5.9 in my bench suite: (still this is not blocking a release) 

### 5.9 

```
tiny post sanitize: true
                        129.364  (±10.8%) i/s -    636.000  in   5.014269s
giant post sanitize: true
                        106.396  (±10.3%) i/s -    530.000  in   5.073153s
most features sanitize: true
                         54.285  (± 7.4%) i/s -    272.000  in   5.039917s
lots of mentions sanitize: true
                          0.404  (± 0.0%) i/s -      3.000  in   7.428951s
tiny post sanitize: false
                        284.413  (± 8.8%) i/s -      1.430k in   5.071733s
giant post sanitize: false
                        207.441  (± 7.2%) i/s -      1.050k in   5.092453s
most features sanitize: false
                         74.881  (± 6.7%) i/s -    378.000  in   5.071991s
lots of mentions sanitize: false
                          0.403  (± 0.0%) i/s -      3.000  in   7.441425s
markdown it no extensions commonmark tiny post
                          7.832k (± 4.3%) i/s -     39.744k in   5.083833s
markdown it no extensions commonmark giant post
                        916.757  (± 9.5%) i/s -      4.550k in   5.054635s
markdown it no extensions commonmark most features
                          1.493k (± 6.3%) i/s -      7.560k in   5.087277s
markdown it no extensions commonmark lots of mentions
                          2.089k (± 5.5%) i/s -     10.556k in   5.070508s
```

### 6.3

```
tiny post sanitize: true
                        129.675  (±10.8%) i/s -    648.000  in   5.070792s
giant post sanitize: true
                        106.214  (±10.4%) i/s -    530.000  in   5.057866s
most features sanitize: true
                         52.109  (±11.5%) i/s -    260.000  in   5.054359s
lots of mentions sanitize: true
                          0.335  (± 0.0%) i/s -      2.000  in   5.988207s
tiny post sanitize: false
                        257.299  (±10.9%) i/s -      1.288k in   5.073169s
giant post sanitize: false
                        208.196  (± 9.6%) i/s -      1.050k in   5.093251s
most features sanitize: false
                         75.199  (± 6.6%) i/s -    378.000  in   5.053536s
lots of mentions sanitize: false
                          0.393  (± 0.0%) i/s -      2.000  in   5.091215s
markdown it no extensions commonmark tiny post
                          7.643k (± 4.3%) i/s -     38.743k in   5.078730s
markdown it no extensions commonmark giant post
                        934.341  (±12.2%) i/s -      4.592k in   5.079925s
markdown it no extensions commonmark most features
                          1.472k (± 3.6%) i/s -      7.452k in   5.068865s
markdown it no extensions commonmark lots of mentions
                          2.054k (± 6.9%) i/s -     10.400k in   5.095029s
```

Benchmark is: https://github.com/discourse/discourse/blob/master/script/benchmarks/markdown/bench.rb

**Comment by ignisf** [comment] 2017-12-20 16:05
.0 and .1 releases are up on rubygems.

**Comment by seanmakesgames** [comment] 2017-12-20 20:22
prepping to run the suite on this (have been making changes, so want to make sure tests are passing first) ;)
Will be running tests against 6.3.292.48.1 and let you know how it goes.

**Comment by seanmakesgames** [comment] 2017-12-20 21:12
everything looks good on my end. tests pass. no funky behavior (more than usual) :P

**Comment by SamSaffron** [comment] 2017-12-22 07:05
It is holiday season, I will try to get a new stable out next week, but will only upgrade Discourse the week after

**Comment by SamSaffron** [comment] 2017-12-27 21:53
thanks heaps @ignisf  for the work on libv8 6.3 we now have a new release.

**Closed** 2017-12-27 21:53 UTC

**Comment by Napolskih** [comment] 2018-01-25 14:44
What about 6.4? They [promise](https://v8project.blogspot.ru/2017/12/v8-release-64.html) a significant optimization.

**Comment by ignisf** [comment] 2018-01-25 15:22
I too am eager to push libv8 6.4. Just have to find some time to do so.
